---
# defaults/main.yml for vast_cluster_setup

# Target host
vast_cluster_setup_host: ""

# Authentication
vast_cluster_setup_username: ""
vast_cluster_setup_password: ""
vast_cluster_setup_api_key: ""

# Behavior
vast_cluster_setup_validate_certs: true
vast_cluster_setup_state: present
