---
dependency:
  name: galaxy
driver:
  name: delegated
  options:
    managed: false
    ansible_connection_options:
      ansible_connection: local
platforms:
  - name: localhost
    managed: false
provisioner:
  name: ansible
  env:
    ANSIBLE_COLLECTIONS_PATH: "${ANSIBLE_COLLECTIONS_PATH:-../../../..}"
  inventory:
    hosts:
      all:
        hosts:
          localhost:
            ansible_connection: local
verifier:
  name: ansible
