---
# defaults/main.yml for vast_view_provision

# Target host
vast_view_provision_host: ""

# Authentication
vast_view_provision_username: ""
vast_view_provision_password: ""
vast_view_provision_api_key: ""

# Behavior
vast_view_provision_validate_certs: true
vast_view_provision_state: present
