---
# defaults/main.yml for vast_user_management

# Target host
vast_user_management_host: ""

# Authentication
vast_user_management_username: ""
vast_user_management_password: ""
vast_user_management_api_key: ""

# Behavior
vast_user_management_validate_certs: true
vast_user_management_state: present
