---
- name: "Vastdata Alert Remediation"
  hosts: all
  sources:
    - stevefulme1.vastdata.vast_webhook:
        host: 127.0.0.1
        port: 5000
  rules:
    - name: Critical alert
      condition: event.vastdata is defined
      action:
        run_playbook:
          name: remediate.yml
          extra_vars:
            alert: "{{ event.vastdata }}"
