---
# defaults/main.yml for vast_capacity_expansion

# Target host
vast_capacity_expansion_host: ""

# Authentication
vast_capacity_expansion_username: ""
vast_capacity_expansion_password: ""
vast_capacity_expansion_api_key: ""

# Behavior
vast_capacity_expansion_validate_certs: true
vast_capacity_expansion_state: present
