---
# defaults/main.yml for vast_s3_setup

# Target host
vast_s3_setup_host: ""

# Authentication
vast_s3_setup_username: ""
vast_s3_setup_password: ""
vast_s3_setup_api_key: ""

# Behavior
vast_s3_setup_validate_certs: true
vast_s3_setup_state: present
